apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
  labels:
    app: nginx
    component: helm
  #these labels belong to deployment set resource
spec:
  replicas: {{ .Values.controller.replicaCount }} #specify no. of pods, as per our requirement
  selector: #select the pods with these labels
    matchLabels:
      component: helm
      app: nginx
    #below mentioned code refers to pod definition
  template:
    metadata:
      labels:
        component: helm
        app: nginx
        project: testing
    spec:
      containers:
      - name: nginx-ingress-controller
      image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
      args:
        - /nginx-ingress-controller
        - --ingress-class={{ .Values.controller.extraArgs.ingressclass }}
  
